# Generated by Django 5.1.2 on 2024-10-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_boxes', models.IntegerField()),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Delivered', 'Delivered'), ('Dispatched', 'Dispatched')], default='Booked', max_length=12)),
                ('date_booked', models.DateField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.consignee')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.consignor')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.district')),
            ],
            options={
                'db_table': 'booking_table',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='pending', max_length=9)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.booking')),
            ],
            options={
                'db_table': 'delivery_table',
            },
        ),
        migrations.CreateModel(
            name='Despatch',
            fields=[
                ('despatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.vehicle')),
            ],
            options={
                'db_table': 'despatch_table',
            },
        ),
    ]
