# Generated by Django 5.1.2 on 2024-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0002_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despatch',
            name='booking',
        ),
        migrations.AddField(
            model_name='despatch',
            name='booking',
            field=models.ManyToManyField(to='Staffapp.booking'),
        ),
    ]
