# Generated by Django 5.1.2 on 2024-10-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0004_booking_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField()),
                ('barcode_image', models.ImageField(upload_to='barcodes/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_barcodes', to='Staffapp.booking')),
            ],
            options={
                'db_table': 'box_barcode_table',
                'unique_together': {('booking', 'box_number')},
            },
        ),
    ]
